[2025-06-02T15:33:11.228+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: test_spark_connection.test_spark_task manual__2025-06-02T15:33:07.626133+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
